export const frasesDeTerror = [
    "Ouvi um sussurro no escuro.",
    "A luz apagou e a porta se fechou sozinha.",
    "Há alguém me observando através da janela.",
    "As vozes na minha cabeça estão ficando mais altas.",
    "Vi uma sombra se mover rapidamente pelo corredor.",
    "A boneca se mexeu quando ninguém estava olhando.",
    "Há sangue escorrendo pelas paredes.",
    "O espelho refletiu uma figura que não estava lá.",
    "Ouvi risadas macabras no porão.",
    "As fotografias nas paredes mudaram sozinhas.",
    "A TV ligou sozinha e mostrou imagens perturbadoras.",
    "Há arranhões profundos na porta.",
    "O relógio parou exatamente à meia-noite.",
    "Sinto uma presença fria atrás de mim.",
    "Ouvem-se passos no sótão vazio.",
    "Algo puxou minha coberta enquanto eu dormia.",
    "A cadeira de balanço está se movendo sozinha.",
    "A janela abriu com um rangido aterrorizante.",
    "O rádio está tocando uma música antiga e assombrosa.",
    "Encontrei uma mensagem escrita com sangue no espelho.",
    "As paredes parecem estar sussurrando segredos.",
    "Os olhos da pintura na parede estão me seguindo.",
    "Sinto que algo está rastejando sob a minha pele.",
    "A porta do armário se abre lentamente à noite.",
    "Há pegadas molhadas no chão, mas está seco lá fora.",
    "Ouvi um grito abafado vindo do porão.",
    "Minha sombra não está se movendo como eu.",
    "Os brinquedos estão dispostos em uma formação perturbadora.",
    "Senti um sopro frio no meu pescoço.",
    "A água da torneira está saindo vermelha.",
    "Vi um rosto estranho refletido na janela.",
    "O telefone tocou, mas ninguém respondeu.",
    "Há uma presença invisível no quarto.",
    "Ouvem-se gemidos vindos do corredor.",
    "O vento está uivando, mas todas as janelas estão fechadas.",
    "Algo está arranhando debaixo da cama.",
    "As portas do armário batem sozinhas.",
    "Ouvi um sussurro dizendo meu nome.",
    "A figura no espelho está sorrindo para mim.",
    "Há marcas de garras no teto.",
    "A estátua no jardim está olhando diretamente para a casa.",
    "Sinto um par de olhos invisíveis me observando.",
    "Ouvi uma canção de ninar vinda de um quarto vazio.",
    "A porta do porão está entreaberta e algo está olhando para fora.",
    "As luzes piscam e posso ver figuras sombrias.",
    "Algo está tocando meu ombro, mas estou sozinho.",
    "Os quadros estão inclinados de forma estranha.",
    "A porta do quarto trancada está se abrindo lentamente.",
    "Os objetos estão se movendo sozinhos pela casa.",
    "O relógio de parede está tic-tacando ao contrário."
]
